version: '2'

services: 

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes: 
      - ./src:/api/src
      - ./config:/api/config
    env_file:
      - var.env
    ports:
      - "3000:3000"

  nginx:
    image: prayforhana/nginx:0.1.1
    links:
      - nodejs:nodejs
    ports:
      - "80:80"
      