version: '2'

services: 

  nodejs:
    build: .
    volumes: 
      - ./lib:/api/lib
      - ./config:/api/config
    env_file:
      - var.env
    ports:
      - "3000:3000"

  frontend:
    image: prayforhana/test3:0.1
    links:
      - nodejs:nodejs
    ports:
      - "80:80"
      